### ISSUE TITLE
Remove -for-go suffix

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/azure-vhd-utils#18]
I think we can use mitchellh/gox and provide signed cross-platform binary releases on GitHub.

There's no point of mentioning this being a Go package in README or in the repo name?

**Comment by anuchandy** [comment]
@ahmetalpbalkan thanks for the suggestion.

@martinsawicki - do we need to get buy-in from legal to rename the repo?

**Comment by ahmetalpbalkan** [comment]
@anuchandy I don't think you need a legal check. @jeffwilcox knows maybe.

**Comment by ahmetalpbalkan** [comment]
ping

**Comment by anuchandy** [comment]
@ahmetalpbalkan done! updated url https://github.com/Microsoft/azure-vhd-utils

**Comment by ahmetalpbalkan** [comment]
❤️ 💚 💜 💛
