### ISSUE TITLE
Document benefits/why

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/azure-vhd-utils#28]
It would be good to have a bullet list enumerating why this should be preferred over the `azure storage blob upload` command in the README.

**Comment by anuchandy** [comment]
@ahmetalpbalkan do you think you can contribute this to the readme?

**Comment by ahmetalpbalkan** [comment]
I have neither used the tool myself nor I know about the optimizations/benefits unfortunately. 🌵 

@colemickens to rescue.

**Comment by colemickens** [comment]
Let me know if this is sufficient. https://github.com/Microsoft/azure-vhd-utils/pull/29
