### ISSUE TITLE
How can I install this tool on windows?

### ISSUE THREAD

**Issue by wangjj1989** [Microsoft/azure-vhd-utils#37]
I encounter the dynamic vhd uploading issue and I need this tool to upload my dynamic linux vhd.
But I must use windows to do this work.
Does this tool only support linux ? How can I install it on windows?
Actually, I am a little disappointed at Microsoft, which I cannot do all the work by *Azure Powershell CLI* but to install the other tools to do the job.

**Comment by anuchandy** [comment]
The tool is written in Go so you will be able to run it in any OS that supports Go, including Windows.

Refer the readme file https://github.com/Microsoft/azure-vhd-utils/blob/master/README.md

**Comment by wangjj1989** [comment]
Yes, I have read it.
I installed go and gitshell and run the command (go get github.com/Microsoft/azure-vhd-utils-for-go) in gitshell but it didn't  work. So I am here.

**Comment by anuchandy** [comment]
can you try from the regular Windows command prompt ?

Also just to make sure go is installed properly - can you check whether you can run basic go hello world as per https://golang.org/doc/install

**Comment by wangjj1989** [comment]
Thanks. My bad. Gitshell not working, need to install git.
We can close it.
