### ISSUE TITLE
Error building azure-vhd-utils: cannot use blobServiceClient

### ISSUE THREAD

**Issue by ctaymor** [Microsoft/azure-vhd-utils#42]
When attempting to `go get -u github.com/Microsoft/azure-vhd-utils-for-go`, I get the following error:
```
$HOME/go/src/github.com/Microsoft/azure-vhd-utils-for-go/vhdUploadCmdHandler.go:158: cannot use blobServiceClient (type "github.com/Microsoft/azure-vhd-utils-for-go/vendor/github.com/Azure/azure-sdk-for-go/storage".BlobStorageClient) as type "github.com/Microsoft/azure-vhd-utils/vendor/github.com/Azure/azure-sdk-for-go/storage".BlobStorageClient in field value
$HOME/go/src/github.com/Microsoft/azure-vhd-utils-for-go/vhdUploadCmdHandler.go:212: cannot use client (type "github.com/Microsoft/azure-vhd-utils-for-go/vendor/github.com/Azure/azure-sdk-for-go/storage".BlobStorageClient) as type "github.com/Microsoft/azure-vhd-utils/vendor/github.com/Azure/azure-sdk-for-go/storage".BlobStorageClient in argument to metadata.NewMetadataFromBlob
```

When I attempted this, the latest commit was 43293b8d76460dd25093d216c95abc79342e1657

**Comment by anuchandy** [comment]
Can you remove any reference to older version of this tool and it's dependencies from your machine? 

github.com/Microsoft/azure-vhd-utils-for-go
github.com/Azure/azure-sdk-for-go/storage
github.com/codegangsta/cli

Remove all these references from bin, src, pkg.

Then try - go get -u github.com/Microsoft/azure-vhd-utils

**Comment by arnottcr** [comment]
Even after making these changes (I am building the binary in an isolated GOROOT), there is no improvement.

**Comment by ctaymor** [comment]
@anuchandy Removing all reference to the older version and dependencies was sufficient to fix the problem for us.

**Comment by anuchandy** [comment]
@ctaymor thanks for confirming.
